name: 'semver-action'
description: 'Semantic Versioning (SemVer) Autoincrement Based on Tag Value'
author: 'Andrii Ivanov'

# Define your inputs here.
inputs:
  repository:
    description: 'Repository name'
    required: true
  github_token:
    description:
      'Token to get tags from the repo. Pass in using `secrets.GITHUB_TOKEN`.'
    required: true

# Define your outputs here.
outputs:
  version:
    description: 'Incremented version'

runs:
  using: node20
  main: dist/index.js
